### PR TITLE
style: changed Chakra UI to dark theme

### PR DESCRIPTION
**Pull request by flohoch**

### CODE REVIEW

**Comment by philprime** [comment]
I think we should do something about "Create new account" and "forgot password" being unreadable with that low contrast between purple font color and black background

image

CC @copieman

**Comment by philprime** [comment]
Maybe the date picker should also use the dark theme

image

**Comment by philprime** [comment]
In general the low contrast between text and background takes a big toll on usability.
There is no more distinction between placeholders and the acutal entered text in the textfields.

image

**Comment by philprime** [comment]
@copieman @flohoch it might be a good idea to look at the colors on a lower-/mid-quality monitor. The contrast might be good on an iMac or on an Apple Studio display, but when I tested it I used my "normal" Samsung Monitors and it was sunny inside and outside

**Comment by copieman** [comment]
Changes @flohoch 

- Button Text like create new Account etc. get the new color "light purple" #BC92E4 (it's WCAG compliant)
- The Text Color #8E8E93 that I selected is also WCAG compliant, so check if in the second picture it's rightly chosen
- Date Picker dark if possible of course, makes sense
- Text, when typed in should be white #FFFFFF

**Comment by philprime** [comment]
Closed in favour of #1176 and upcoming adaptions

**Pull request closed without merging**
